internetarchive/iari

requirements.txt
src/__init__.py
src/models/cache.py
src/models/ssdb_database.py
src/models/wikicitations/__init__.py
src/models/wikimedia/wikipedia/wikipedia_page.py
tests/test___init__.py
tests/test_cache.py
tests/test_ssdb_aws_database.py
tests/test_ssdb_database.py
tests/test_wikicitations.py

This enables deleting both the cache and all items in the Wikibase and iterating on the datamodel.

Implement rinse functionality

---

wcdimportbot.py

Fix a typo

---

src/models/wikimedia/wikipedia/templates/wikipedia_page_reference.py

Thanks to @cclauss who discovered the bug and provided the fix in #17

Fix bug in first_parameter and add check and logging

---

README.md
src/models/wikimedia/wikipedia/templates/wikipedia_page_reference.py
wcdimportbot.py

* Make `wcdimportbot.py` executable and improve the shebang line to find the best Python.
* README.md
* Keep formatting of supported_templates
* Add instructions for creating and activating a [virtual environment](https://docs.python.org/3/library/venv.html)
* Update to the current usage text

Suggestions for a smoother setup pocess

---

src/models/wikicitations/__init__.py
src/models/wikicitations/enums.py
src/models/wikicitations/itemtypes/base_item_type.py
src/models/wikicitations/itemtypes/website_item.py
src/models/wikicitations/itemtypes/wikipedia_page.py
src/models/wikicitations/itemtypes/wikipedia_reference.py
tests/test_english_wikipedia_page_reference.py
tests/test_wikicitations.py

This makes it possible for us to entity link them to Wikidata later. E.g. "Stockholm" -> Q1754

Support publisher and location strings also

---

src/models/wikicitations/__init__.py
src/models/wikimedia/wikipedia/wikipedia_page.py
tests/test_wikicitations.py

Wikibase do not support > 250 characters in the label.

Honor label max length

---

src/__init__.py
src/models/cache.py
src/models/person/__init__.py
src/models/ssdb_database.py
src/models/wikicitations/__init__.py
src/models/wikicitations/itemtypes/base_item_type.py
src/models/wikimedia/wikidata/item.py
src/models/wikimedia/wikipedia/templates/wikipedia_page_reference.py
src/models/wikimedia/wikipedia/wikipedia_page.py
src/wcd_base_model.py

This enables logging to file from any class.

Implement new WcdBaseModel

---

setup_all_properties_and_items_on_new_wikibase.py
src/models/wikibase/__init__.py
src/models/wikibase/dictionaries.py
src/models/wikibase/sandbox_wikibase.py
src/models/wikibase/wikicitations_wikibase.py
src/models/wikicitations/__init__.py

CHAPTER_URL, CONFERENCE_URL, LAY_URL and TRANSCRIPT_URL.

Support 4 more URL fields

---

src/models/wikibase/dictionaries.py
src/models/wikicitations/enums.py

Support ARCHIVE_TODAY and WEBCITATION_ORG also

Support 2 more archives

---

src/models/wikibase/__init__.py

Add default docker Wikibase sparql endpoint url

---

setup_all_properties_and_items_on_new_wikibase.py

Fix setting up properties and base items

---

src/models/wikimedia/wikipedia/templates/google_books.py
src/models/wikimedia/wikipedia/templates/wikipedia_page_reference.py
tests/test_google_books.py

https://en.wikipedia.org/wiki/Template:Google_books

Support Google Books template

---

setup_all_properties_and_items_on_new_wikibase.py
src/models/wikibase/__init__.py
src/models/wikibase/dictionaries.py
src/models/wikibase/sandbox_wikibase.py
src/models/wikicitations/__init__.py
src/models/wikimedia/wikipedia/templates/wikipedia_page_reference.py
tests/test_english_wikipedia_page_reference.py
tests/test_wikicitations.py

This detects and adds the INTERNET_ARCHIVE_ID to all references.

Support INTERNET_ARCHIVE_ID

---

src/models/wikibase/__init__.py
src/models/wikibase/dictionaries.py
src/models/wikibase/sandbox_wikibase.py
src/models/wikibase/wikicitations_wikibase.py
src/models/wikicitations/__init__.py
src/models/wikimedia/wikipedia/templates/wikipedia_page_reference.py
tests/test_english_wikipedia_page_reference.py
tests/test_wikicitations.py

Detect and populate a new external-id property.

Support GOOGLE_BOOKS_ID

---

src/models/wikibase/__init__.py
src/models/wikibase/dictionaries.py
src/models/wikibase/sandbox_wikibase.py
src/models/wikicitations/__init__.py
tests/test_english_wikipedia_page_reference.py
tests/test_wikicitations.py

Add external-id property for it and populate it.

Support OCLC control number

---

src/__init__.py
src/models/wikibase/crud/__init__.py
src/models/wikibase/crud/read.py
src/models/wikibase/crud/update.py
tests/test_wcdimportbot.py
tests/test_wikibase_crud_read.py
tests/test_wikibase_crud_update.py

Add support for rebuilding the cache

---

.pre-commit-config.yaml
development-requirements.txt
requirements.txt
src/models/wikibase/crud/create.py
src/models/wikibase/crud/update.py
tests/test_wikibase_crud_update.py

Fix modification failed

---

src/models/wikibase/crud/__init__.py
src/models/wikimedia/wikipedia/templates/wikipedia_page_reference.py
tests/test_english_wikipedia_page_reference.py
tests/test_wikibase_crud_create.py

Fix bug with detection of archive url

---

wcdimportbot.py

This only works if https://github.com/LeMyst/WikibaseIntegrator/pull/407 is merged.

Hide WBI errors

---

src/__init__.py
src/models/cache/cache_return.py
src/models/return_.py
src/models/wcd_item.py
src/models/wikibase/crud/__init__.py
src/models/wikibase/crud/update.py
src/models/wikimedia/wikipedia/templates/wikipedia_reference.py
src/models/wikimedia/wikipedia/wikipedia_article.py
tests/test_english_wikipedia_page_reference.py
tests/test_wikibase_crud_create.py
tests/test_wikibase_crud_update.py
tests/test_wikipedia_page.py

Reverts internetarchive/wcdimportbot#115

Revert "Remove SPARQL lookup"

---

src/models/wikibase/crud/__init__.py
src/models/wikibase/crud/read.py
src/models/wikibase/website.py
src/models/wikimedia/wikipedia/references/wikipedia.py
src/models/wikimedia/wikipedia/wikipedia_article.py
tests/test_website.py
tests/test_wikibase_crud_create.py
tests/test_wikibase_crud_update.py

This further decreases the complexity of WikipediaArticle

New class Website

---

src/__init__.py
src/helpers/wbi.py
src/models/message.py
src/models/wikibase/crud/create.py
src/models/wikibase/crud/delete.py
src/models/wikibase/crud/update.py
src/models/wikibase/enums.py
src/models/wikimedia/wikipedia/article.py
src/models/wikimedia/wikipedia/reference/generic.py
src/models/wikimedia/wikipedia/wikipedia_article.py
src/models/work_queue.py
src/wcd_base_model.py
src/wcd_wikibase_model.py
tests/test_english_wikipedia_page_reference.py
tests/test_wcdimportbot.py
tests/test_wikibase_crud_update.py
tests/test_wikipedia_article.py

Rewrite to avoid password leak

---

src/models/wikimedia/wikipedia/reference/english/google_books.py
tests/test_google_books.py

Fix google books page parse error

---

src/models/wikimedia/wikipedia/reference/english/google_books.py
src/models/wikimedia/wikipedia/reference/generic.py
tests/test_english_wikipedia_page_reference.py
tests/test_google_books.py

We need to rethink the model before supporting it.
fixes #148

Deprecate google books support

---

wcdimportbot.py

Improve logging format

---

src/models/wikimedia/wikipedia/reference/generic.py
tests/crud/test_wikibase_crud_create.py
tests/crud/test_wikibase_crud_update.py
tests/test_english_wikipedia_page_reference.py
tests/test_wikipedia_article.py

Add testing for all hashing of identifiers to ensure correctness
fixes #257 
fixes #247

Fix hashing based on url

---

src/__init__.py
src/models/wikibase/__init__.py
src/models/wikibase/crud/__init__.py
src/models/wikibase/crud/read.py
tests/crud/test_wikibase_crud_read.py
tests/test_wikibase.py

Fix rebuild cache and wikibase url slash-issue

---

src/models/api/lookup_wikicitations_qid.py
src/models/wikibase/__init__.py
src/models/wikibase/crud/__init__.py
src/models/wikibase/crud/read.py
tests/test_wikibase.py

use new testable property methods and thest them
fixes #273

Fix rdf prefix urls

---

README.md

Add terminology

---

INVESTIGATIONS.md
src/models/wikimedia/wikipedia/article.py
src/models/wikimedia/wikipedia/reference/generic.py
tests/test_hashing.py
user_scripts/ia-sandbox-add-job.js

Add new add-job user script

---

user_scripts/ia-sandbox-link.js

New user script ia-sandbox-link

---

src/models/api/lookup_by_wikidata_qid.py
src/models/api/lookup_wikicitations_qid.py
src/models/wikibase/__init__.py

fixes #312
fixes #311
fixes #313

Fix no match bug in the wikidata-qid endpoint

---

src/models/api/enums.py
src/models/api/lookup_by_wikidata_qid.py
src/models/api/lookup_wikicitations_qid.py

Honor wikibase configuration variable

---

ADD_TEMPLATE.md
config_sample.py
tests/reference/test_english_wikipedia_page_reference.py

Support cite dictionary

---

src/__init__.py
src/models/wikibase/crud/delete.py

Deprecate WikibaseCrudDelete

---

run-worker.py
src/__init__.py
src/helpers/template_extraction.py
src/models/api/add_job_schema.py
src/models/message.py
src/models/update_delay.py
src/models/wikimedia/wikipedia/reference/english/google_books.py
src/models/wikimedia/wikipedia/reference/english/schema.py
src/models/work_queue.py
tests/event/test_message.py
tests/test_update_delay.py
tests/work_queue/test_message.py
tests/work_queue/test_work_queue.py

Fix message cache issue

---

src/models/wikimedia/wikipedia/article.py

Disable import of articles with 500+ references

---

src/models/wikibase/crud/__init__.py

Simplify to no longer require the WikipediaArticle just for setting the description on the reference.

Fix descriptions

---

src/models/wikimedia/wikipedia/reference/english/google_books.py
src/models/wikimedia/wikipedia/reference/generic.py
tests/reference/test_google_books.py

Improve handling of invalid google books id

---

RELEASE.md
poetry.lock
pyproject.toml

Prepare release 3.0.0-alpha0

---

.pre-commit-config.yaml
src/models/api/article_statistics.py
src/models/api/reference_statistics.py
src/models/wikimedia/wikipedia/analyzer.py
src/models/wikimedia/wikipedia/reference/extractor.py
src/models/wikimedia/wikipedia/reference/raw_reference.py
tests/api/test_get_article_statistics.py
tests/wikipedia/reference/test_extractor.py
tests/wikipedia/reference/test_raw_reference.py
tests/wikipedia/test_analyzer.py

Add more quantifiable information about the article and references
fixes #504
fixes #494

Add statistics for references to get_statistics

---

src/models/api/article_statistics.py
src/models/wikimedia/wikipedia/analyzer.py
src/models/wikimedia/wikipedia/reference/extractor.py
tests/api/test_get_article_statistics.py
tests/wikipedia/reference/test_extractor.py
tests/wikipedia/test_analyzer.py
tests/wikipedia/test_article.py

Rename API attribute

---

src/models/wikimedia/wikipedia/reference/raw_reference.py
tests/wikipedia/reference/test_raw_reference.py

Detect wayback url

---

src/models/wikimedia/wikipedia/reference/raw_reference.py
tests/wikipedia/reference/test_raw_reference.py

Detect archive details urls

---

src/models/wikimedia/wikipedia/reference/raw_reference.py
tests/wikipedia/reference/test_raw_reference.py

Detect books.google.com

---

src/models/wikimedia/wikipedia/url.py
tests/wikipedia/test_url.py

Fix 500 errors caused by url exceptions

---

src/models/api/get_article_statistics/__init__.py
src/models/api/get_article_statistics/article_statistics.py
src/models/api/get_article_statistics/references/__init__.py
src/models/wikimedia/wikipedia/analyzer.py
src/models/wikimedia/wikipedia/article.py
tests/api/test_get_article_statistics.py
tests/wikipedia/test_analyzer.py

fixes #579
fixes #577
fixes #560

Add timing, timestamp, page_id, lang and site

---

src/models/wikimedia/wikipedia/reference/raw_reference.py
src/models/wikimedia/wikipedia/reference/template.py
src/models/wikimedia/wikipedia/url.py
tests/wikipedia/test_url.py

Support detecting IP adresses 

---

src/models/api/get_article_statistics/references/links.py
src/models/api/get_article_statistics/references/links_aggregates.py
src/models/wikimedia/wikipedia/analyzer.py
src/models/wikimedia/wikipedia/reference/extractor.py
tests/api/test_get_article_statistics.py

Support more detailed agg in Links

---

config_sample.py
src/models/api/get_article_statistics/references/content/aggregate/__init__.py
src/models/wikimedia/wikipedia/analyzer.py
src/models/wikimedia/wikipedia/reference/extractor.py
src/models/wikimedia/wikipedia/reference/raw_reference.py
tests/api/test_get_article_statistics.py
tests/wikipedia/test_analyzer.py

Add support for deprecated reference templates

---

config_sample.py
debug_app.py
src/models/api/__init__.py
src/models/api/get_article_statistics/__init__.py
src/models/api/get_article_statistics/references/__init__.py
src/models/api/get_article_statistics/references/reference_statistics.py
src/models/api/job.py
src/models/file_io.py
src/models/wikimedia/wikipedia/analyzer.py
src/models/wikimedia/wikipedia/reference/extractor.py
src/models/wikimedia/wikipedia/reference/raw_reference.py
src/models/wikimedia/wikipedia/url.py
test_data/test_content.py
tests/api/test_get_article_statistics.py
tests/api/test_job.py
tests/test_file_io.py
tests/wikipedia/reference/test_extractor.py
tests/wikipedia/reference/test_raw_reference.py
tests/wikipedia/test_analyzer.py
tests/wikipedia/test_url.py
wsgi.py

Support json disk input/output

---

src/models/wikimedia/wikipedia/analyzer.py
src/models/wikimedia/wikipedia/reference/extractor.py
tests/wikipedia/reference/test_extractor.py

Fix bug with check_urls

---

src/models/wikimedia/wikipedia/reference/extractor.py
src/models/wikimedia/wikipedia/url.py
tests/wikipedia/reference/test_extractor.py
tests/wikipedia/reference/test_raw_reference.py
tests/wikipedia/test_url.py

Rewrite WikipediaUrl to improve it

---

src/models/wikimedia/wikipedia/reference/extractor.py
test_data/test_content.py
tests/wikipedia/reference/test_extractor.py

Support more sections with references

---

src/models/api/get_article_statistics/__init__.py
src/models/api/get_article_statistics/article_statistics.py
src/models/api/get_article_statistics/get_statistics_schema.py
src/models/api/job.py
src/models/file_io.py
src/models/wikimedia/wikipedia/url.py
tests/api/test_get_article_statistics.py
tests/api/test_job.py
tests/test_file_io.py
tests/test_get_statistics_schema.py
tests/wikipedia/test_url.py

Add support for refresh argument

---

.pre-commit-config.yaml
poetry.lock
pyproject.toml

Use dead to find dead code

---

README.md
poetry.lock
pyproject.toml
src/models/identifiers_checking/doi.py
tests/checking/test_doi.py

Add support for lookup in fatcat

---

diagrams/wari/classes.puml
src/models/identifiers_checking/doi.py
tests/checking/test_doi.py

Also structure similarly to openalex and wikidata to avoid making data consumers think.

Extract id from fatcat

---

src/models/identifiers_checking/doi.py
tests/checking/test_doi.py

Support ia sholar also in check-doi

---

src/models/api/job/__init__.py
src/views/check_doi.py
src/views/check_url.py
src/views/statistics/__init__.py
src/views/statistics/all.py
src/views/statistics/article.py
src/views/statistics/references.py
src/views/statistics/write_view.py

Support cache and refresh on article, all, and the checking endpoints

---

src/models/api/statistics/article/__init__.py
src/models/wikimedia/wikipedia/analyzer.py

Expose all dehydrated references in the article endpoint

---

src/models/api/all.py
src/models/identifiers_checking/url.py
tests/api/test_all_handler.py
tests/checking/test_url.py

Add spoofing headers to check-url

---

src/models/api/job/article_job.py
src/models/api/schema/article_schema.py
tests/api/test_article.py
tests/api/test_article_job.py
tests/test_get_statistics_schema.py

Deprecate lang+site+title

---

src/models/wikimedia/wikipedia/reference/template/template.py
tests/wikipedia/reference/test_template.py

Extract ISBNs

---

src/models/wikimedia/wikipedia/reference/extractor.py
tests/test_get_statistics_schema.py
tests/wikipedia/reference/test_extractor.py
tests/wikipedia/reference/test_raw_reference.py
tests/wikipedia/reference/test_template.py
tests/wikipedia/test_analyzer.py
tests/wikipedia/test_wikipedia_article.py

Filter lines in sections to avoid false positives

---

src/__init__.py
src/models/api/all.py
src/models/api/statistic/article.py
src/models/basemodels/job.py
src/models/file_io/__init__.py
src/models/file_io/references.py
src/models/identifiers_checking/url.py
src/models/wcd_item.py
src/models/wikimedia/wikipedia/analyzer.py
src/models/wikimedia/wikipedia/article.py
src/models/wikimedia/wikipedia/reference/extractor.py
src/models/wikimedia/wikipedia/reference/generic.py
src/models/wikimedia/wikipedia/reference/template/persons.py
src/models/wikimedia/wikipedia/url.py
src/views/statistics/__init__.py
tests/api/test_article.py
tests/api/test_article_job.py
tests/test_get_statistics_schema.py
tests/wikipedia/reference/test_english_wikipedia_page_reference.py
tests/wikipedia/reference/test_raw_reference.py
tests/wikipedia/test_wikipedia_article.py
tests/wikipedia/test_wikipedia_url.py
wcdimportbot.py

Fix all tests

---

src/models/identifiers_checking/url.py

Allow redirects to avoid 3xx status codes

---

src/models/exceptions.py
src/models/wikimedia/wikipedia/analyzer.py
src/models/wikimedia/wikipedia/article.py
src/models/wikimedia/wikipedia/reference/english/schema.py
src/models/wikimedia/wikipedia/reference/enums.py
src/models/wikimedia/wikipedia/reference/extractor.py
src/models/wikimedia/wikipedia/reference/generic.py
src/models/wikimedia/wikipedia/reference/template/person/__init__.py
src/models/wikimedia/wikipedia/reference/template/person/english_wikipedia_template_person.py
src/views/statistics/__init__.py
src/views/statistics/references.py
tests/checking/test_url.py
tests/wikipedia/reference/test_english_wikipedia_page_reference.py
tests/wikipedia/reference/test_extractor.py
tests/wikipedia/reference/test_person.py
tests/wikipedia/test_wikipedia_article.py

Add test for URL which return different status codes over time

---

src/models/identifiers_checking/url.py
src/models/wikimedia/wikipedia/enums.py
src/models/wikimedia/wikipedia/url.py
tests/checking/test_url.py
tests/wikipedia/test_wikipedia_url.py

Rewrite check-url to fix WM urls being reported as malformed urls

---

poetry.lock
pyproject.toml
src/models/api/handlers/pypdf.py
src/views/statistics/pdf.py
tests/api/handler/test_pypdf.py

Switch to pypdf

---

README.md
poetry.lock
pyproject.toml
src/__init__.py
src/models/api/handlers/xhtml.py
src/models/api/link.py
src/models/file_io/xhtml_file_io.py
src/views/statistics/xhtml.py
tests/api/handler/test_pypdf.py
tests/api/handler/test_xhtml.py

New xhtml endpoint

---

poetry.lock
pyproject.toml
src/models/api/handlers/pypdf.py
tests/api/handler/test_pdf_handler.py
tests/api/handler/test_xhtml.py

Cleanup pypdf and make tests pass

---

README.md
src/models/api/handlers/pdf.py
src/models/api/handlers/pypdf.py
src/views/statistics/pdf.py
tests/api/handler/test_pdf_handler.py
tests/api/test_article.py
tests/api/test_pdf.py

Improve pdf endpoint with annotation extraction

---

README.md
src/models/api/handlers/pdf.py
src/views/statistics/pdf.py
tests/api/test_pdf.py

Fix read timout bug

---

poetry.lock
pyproject.toml
src/models/api/handlers/__init__.py
src/models/api/handlers/pdf.py
src/models/api/handlers/xhtml.py
src/models/identifiers_checking/url.py
tests/api/handler/test_pdf_handler.py
tests/api/handler/test_xhtml.py
tests/checking/test_url.py

fixes #810
fixes #811
fixes #812

Add language detection to 3 endpoints

---

KNOWN_DEPLOYED_INSTANCES.md
src/models/wikimedia/wikipedia/analyzer.py
tests/api/handler/test_xhtml.py
tests/wikipedia/test_analyzer.py

Add wikitext output on reference in article endpoint

---

config.py
src/models/api/handlers/pdf.py
src/models/api/statistic/reference.py
src/models/wikimedia/wikipedia/analyzer.py
src/models/wikimedia/wikipedia/reference/generic.py
tests/api/test_article.py
tests/wikipedia/reference/test_english_wikipedia_page_reference.py
tests/wikipedia/reference/test_extractor.py
tests/wikipedia/test_analyzer.py
tests/wikipedia/test_wikipedia_article.py

Fix url regex by using the same as for link extraction from pdfs.
Support name extraction
fixes #746
fixes #834

Improve Reference class

---

src/models/wikimedia/wikipedia/reference/extractor.py
tests/api/test_article.py
tests/wikipedia/reference/test_extractor.py

Fix fld counts

---

src/models/api/job/article_job.py
src/models/file_io/article_file_io.py
src/models/wikimedia/wikipedia/analyzer.py
src/models/wikimedia/wikipedia/article.py
src/views/statistics/article.py
tests/api/test_article.py
tests/api/test_article_job.py

Also update wari_id to handle storing details for multiple revisions of the same article.
fixes #807

Support revisions in article endpoint

---

src/models/api/handlers/pdf.py
tests/api/handler/test_pdf_handler.py

Use 3 different methods instead of one
fixes #853

Rewrite link extraction from text 

---

README.md
src/models/api/handlers/pdf.py
src/models/api/job/check_url_job.py
src/models/api/schema/check_url_schema.py
src/views/statistics/pdf.py

More debug output

---

tests/api/test_pdf.py

Test pdf debug output

---

src/models/identifiers_checking/url.py
src/views/check_url.py
tests/api/test_check_url.py

Use testdeadlink api also

---

src/models/identifiers_checking/url.py
src/views/check_doi.py
src/views/check_url.py
src/views/statistics/article.py
src/views/statistics/pdf.py
src/views/statistics/write_view.py
src/views/statistics/xhtml.py

Rewrite check url logic

---

.github/workflows/lint_python.yml
.gitignore
config_sample.py
pyproject.toml
src/models/identifiers_checking/url.py
tests/api/test_check_url.py
tests/checking/test_url.py

Rewrite check-url with new auth key support and expose errors from testdeadlink

---

.pre-commit-config.yaml
poetry.lock
src/models/api/handlers/all.py
src/models/api/handlers/pdf.py
src/models/api/handlers/xhtml.py
src/models/file_io/__init__.py
src/models/file_io/article_file_io.py
src/models/file_io/doi_file_io.py
src/models/file_io/pdf_file_io.py
src/models/file_io/reference_file_io.py
src/models/file_io/references.py
src/models/file_io/url_file_io.py
src/models/file_io/xhtml_file_io.py
src/models/identifiers_checking/url.py
src/models/wikimedia/wikipedia/analyzer.py
src/models/wikimedia/wikipedia/article.py
src/models/wikimedia/wikipedia/reference/extractor.py
src/models/wikimedia/wikipedia/reference/generic.py
src/views/check_doi.py
src/views/check_url.py
src/views/statistics/article.py
src/views/statistics/pdf.py
src/views/statistics/write_view.py
src/views/statistics/xhtml.py
tests/api/test_check_url.py
tests/checking/test_url.py
tests/wikipedia/reference/test_english_wikipedia_page_reference.py
tests/wikipedia/test_wikipedia_article.py

Cleanup, update dependencies and fix ClassVar issues

---

README.md
src/models/api/job/article_job.py
src/models/api/schema/article_schema.py
src/models/api/statistic/article.py
src/models/file_io/references.py
src/models/wikimedia/wikipedia/analyzer.py
tests/api/test_article_job.py
tests/wikipedia/test_analyzer.py

Add dehydrate parameter to article endpoint

---

pyproject.toml
tests/api/test_check_url.py

Release of non-breaking changes for the current sprint.

Prepare 4.1.2

---

README.md
config_sample.py
src/models/identifiers_checking/url.py
tests/checking/test_url.py

Switch to environment variable for testdeadlink auth key

---

.github/workflows/lint_python.yml
tests/checking/test_url.py

Reenable testdeadlink testing in the CI

---

Dockerfile
RELEASE.md
app_run.py
app_run_debug.py
debug_app.py
pyproject.toml

Reverts internetarchive/iari#902
ruff errors

Revert "set up for Docker"

---

.gitignore
Dockerfile
pyproject.toml
src/__init__.py
src/helpers/get_version.py
src/models/api/job/article_job.py
src/models/api/job/check_url_archive_job.py
src/models/api/job/check_url_job.py
src/models/api/schema/check_url_archive_schema.py
src/models/api/schema/check_url_schema.py
src/models/api/statistic/article.py
src/models/api/statistic/reference.py
src/models/file_io/__init__.py
src/models/file_io/url_archive_file_io.py
src/models/identifiers_checking/url.py
src/models/identifiers_checking/url_archive.py
src/models/mediawiki/section.py
src/models/wikimedia/wikipedia/analyzer.py
src/models/wikimedia/wikipedia/article.py
src/models/wikimedia/wikipedia/reference/extractor.py
src/models/wikimedia/wikipedia/reference/generic.py
src/models/wikimedia/wikipedia/url.py
src/models/wikimedia/wikipedia/url_archive.py
src/views/check_url.py
src/views/check_url_archive.py
src/views/statistics/__init__.py
src/views/statistics/article.py
src/views/version.py
tests/wikipedia/test_wikipedia_article.py

implements caching for archive status

Check url archive

---

Dockerfile
pyproject.toml
src/models/api/job/article_job.py
src/models/api/job/check_url_job.py
src/models/api/schema/check_url_schema.py
src/models/api/statistic/article.py
src/models/api/statistic/reference.py
src/models/identifiers_checking/url.py
src/models/mediawiki/section.py
src/models/wikimedia/wikipedia/analyzer.py
src/models/wikimedia/wikipedia/article.py
src/models/wikimedia/wikipedia/reference/extractor.py
src/models/wikimedia/wikipedia/reference/generic.py
src/models/wikimedia/wikipedia/url.py
src/views/check_url.py
src/views/statistics/article.py
tests/wikipedia/test_wikipedia_article.py

rearranged output properties of /references endpoint.
General tidying up of code in preparation for further changes.

Move name field
